/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Formulaire de connexion
         * @description Retourne le dernier nom d'utilisateur tenté et l'erreur éventuelle de la dernière tentative de connexion.
         */
        get: operations["SecurityController_getLoginForm"];
        put?: never;
        /**
         * Authentification
         * @description Authentifie l'utilisateur avec username/password et retourne un token JWT.
         */
        post: operations["SecurityController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Déconnexion
         * @description Invalide le token JWT de l'utilisateur connecté.
         */
        get: operations["SecurityController_logout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liste des posts (admin)
         * @description Retourne la liste de tous les posts rédigés par l'administrateur connecté.
         */
        get: operations["AdminBlogController_indexAction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/post/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Formulaire de création de post
         * @description Retourne un gabarit vide pour la création d'un nouveau post.
         */
        get: operations["AdminBlogController_newForm"];
        put?: never;
        /**
         * Créer un nouveau post
         * @description Crée un post et l'associe à l'administrateur connecté.
         */
        post: operations["AdminBlogController_newAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/post/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Détails d'un post (admin)
         * @description Retourne les détails d'un post, avec le token CSRF pour la suppression.
         */
        get: operations["AdminBlogController_showAction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/post/{id}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Formulaire d'édition d'un post
         * @description Retourne les données d'un post existant pour les afficher dans un formulaire d'édition.
         */
        get: operations["AdminBlogController_editForm"];
        put?: never;
        /**
         * Mettre à jour un post
         * @description Met à jour le contenu d'un post existant.
         */
        post: operations["AdminBlogController_editAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/post/{id}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Supprimer un post
         * @description Supprime un post après validation du token CSRF.
         */
        post: operations["AdminBlogController_deleteAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liste paginée des articles (page 1)
         * @description Retourne la première page des articles publiés, triés par date décroissante.
         */
        get: operations["BlogController_indexAction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blog/rss.xml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Flux RSS du blog
         * @description Retourne un flux RSS valide contenant les 50 derniers articles publiés.
         */
        get: operations["BlogController_rssAction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blog/page/{page}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liste paginée des articles (page N)
         * @description Retourne la page N des articles publiés. Retourne 400 si le numéro de page est non numérique, 404 si la page dépasse le total disponible.
         */
        get: operations["BlogController_pageAction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blog/posts/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Détail d'un article
         * @description Retourne un article avec ses commentaires associés, identifié par son slug.
         */
        get: operations["BlogController_postShowAction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blog/comment/{postSlug}/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publier un commentaire
         * @description Crée un commentaire sur un article identifié par son slug. Nécessite une authentification. Le contenu doit faire au moins 5 caractères et ne pas contenir de "@".
         */
        post: operations["BlogController_commentNewAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the health status of the application
         */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Formulaire de connexion
         * @description Retourne le dernier nom d'utilisateur tenté et l'erreur éventuelle de la dernière tentative de connexion.
         */
        get: operations["SecurityController_getLoginForm"];
        put?: never;
        /**
         * Authentification
         * @description Authentifie l'utilisateur avec username/password et retourne un token JWT.
         */
        post: operations["SecurityController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Déconnexion
         * @description Invalide le token JWT de l'utilisateur connecté.
         */
        get: operations["SecurityController_logout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/post/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liste des posts (admin)
         * @description Retourne la liste de tous les posts rédigés par l'administrateur connecté.
         */
        get: operations["AdminBlogController_indexAction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/post/new/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Formulaire de création de post
         * @description Retourne un gabarit vide pour la création d'un nouveau post.
         */
        get: operations["AdminBlogController_newForm"];
        put?: never;
        /**
         * Créer un nouveau post
         * @description Crée un post et l'associe à l'administrateur connecté.
         */
        post: operations["AdminBlogController_newAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/post/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Détails d'un post (admin)
         * @description Retourne les détails d'un post, avec le token CSRF pour la suppression.
         */
        get: operations["AdminBlogController_showAction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/post/{id}/edit/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Formulaire d'édition d'un post
         * @description Retourne les données d'un post existant pour les afficher dans un formulaire d'édition.
         */
        get: operations["AdminBlogController_editForm"];
        put?: never;
        /**
         * Mettre à jour un post
         * @description Met à jour le contenu d'un post existant.
         */
        post: operations["AdminBlogController_editAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/post/{id}/delete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Supprimer un post
         * @description Supprime un post après validation du token CSRF.
         */
        post: operations["AdminBlogController_deleteAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blog/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liste paginée des articles (page 1)
         * @description Retourne la première page des articles publiés, triés par date décroissante.
         */
        get: operations["BlogController_indexAction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blog/rss.xml/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Flux RSS du blog
         * @description Retourne un flux RSS valide contenant les 50 derniers articles publiés.
         */
        get: operations["BlogController_rssAction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blog/page/{page}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liste paginée des articles (page N)
         * @description Retourne la page N des articles publiés. Retourne 400 si le numéro de page est non numérique, 404 si la page dépasse le total disponible.
         */
        get: operations["BlogController_pageAction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blog/posts/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Détail d'un article
         * @description Retourne un article avec ses commentaires associés, identifié par son slug.
         */
        get: operations["BlogController_postShowAction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blog/comment/{postSlug}/new/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publier un commentaire
         * @description Crée un commentaire sur un article identifié par son slug. Nécessite une authentification. Le contenu doit faire au moins 5 caractères et ne pas contenir de "@".
         */
        post: operations["BlogController_commentNewAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the health status of the application
         */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginFormResponseDto: {
            /**
             * @description Dernier nom d'utilisateur saisi (vide si première visite)
             * @example john_user
             */
            last_username: string;
            /**
             * @description Message d'erreur de la dernière tentative échouée, null si aucune
             * @example Identifiants invalides.
             */
            error?: Record<string, never> | null;
        };
        LoginDto: {
            /**
             * @description Nom d'utilisateur
             * @example john_user
             */
            username: string;
            /**
             * @description Mot de passe
             * @example password123
             */
            password: string;
        };
        AuthTokenDto: {
            /**
             * @description Token JWT d'accès
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            access_token: string;
        };
        LogoutResponseDto: {
            /**
             * @description Message de confirmation de déconnexion
             * @example Logged out successfully
             */
            message: string;
        };
        TagDto: {
            /**
             * @description Identifiant du tag
             * @example 1
             */
            id: number;
            /**
             * @description Nom du tag
             * @example nestjs
             */
            name: string;
        };
        PostResponseDto: {
            /**
             * @description Identifiant unique du post
             * @example 1
             */
            id: number;
            /**
             * @description Titre du post
             * @example My Blog Post
             */
            title: string;
            /**
             * @description Slug URL-friendly du post
             * @example my-blog-post
             */
            slug: string;
            /**
             * @description Résumé du post
             * @example A brief summary
             */
            summary: string;
            /**
             * @description Contenu complet du post
             * @example Full content here...
             */
            content: string;
            /**
             * @description Date de publication
             * @example 2024-01-01T00:00:00.000Z
             */
            publishedAt: Record<string, never>;
            /**
             * @description Identifiant de l'auteur
             * @example 1
             */
            authorId: number;
            /** @description Liste des tags associés */
            tags?: components["schemas"]["TagDto"][];
            /**
             * @description Token CSRF pour les opérations de suppression
             * @example a1b2c3d4...
             */
            csrf_token?: string;
        };
        CreatePostDto: {
            /**
             * @description Titre du post
             * @example My Blog Post
             */
            title: string;
            /**
             * @description Résumé du post
             * @example A brief summary
             */
            summary: string;
            /**
             * @description Contenu complet du post (minimum 10 caractères)
             * @example Full content here, at least 10 chars.
             */
            content: string;
            /**
             * @description Date de publication (ISO 8601)
             * @example 2024-01-01T00:00:00.000Z
             */
            publishedAt: string;
            /**
             * @description Liste des tags
             * @example [
             *       "nestjs",
             *       "typescript"
             *     ]
             */
            tags?: string[];
        };
        UpdatePostDto: {
            /**
             * @description Nouveau titre du post
             * @example Updated Post Title
             */
            title: string;
            /**
             * @description Nouveau résumé du post
             * @example Updated summary
             */
            summary: string;
            /**
             * @description Nouveau contenu complet (minimum 10 caractères)
             * @example Updated content, at least 10 chars.
             */
            content: string;
            /**
             * @description Nouvelle date de publication (ISO 8601)
             * @example 2024-06-01T00:00:00.000Z
             */
            publishedAt: string;
            /**
             * @description Nouvelle liste de tags
             * @example [
             *       "nestjs"
             *     ]
             */
            tags?: string[];
        };
        DeletePostDto: {
            /**
             * @description Token CSRF requis pour valider la suppression
             * @example abc123def456...
             */
            _token: string;
        };
        BlogTagDto: {
            /**
             * @description Identifiant du tag
             * @example 1
             */
            id: number;
            /**
             * @description Nom du tag
             * @example nestjs
             */
            name: string;
        };
        PostListItemDto: {
            /**
             * @description Identifiant unique du post
             * @example 1
             */
            id: number;
            /**
             * @description Titre du post
             * @example My Blog Post
             */
            title: string;
            /**
             * @description Slug URL-friendly du post
             * @example my-blog-post
             */
            slug: string;
            /**
             * @description Résumé du post
             * @example A brief summary
             */
            summary: string;
            /**
             * @description Contenu complet du post
             * @example Full content here...
             */
            content: string;
            /**
             * Format: date-time
             * @description Date de publication
             * @example 2024-01-01T00:00:00.000Z
             */
            publishedAt: string;
            /**
             * @description Identifiant de l'auteur
             * @example 1
             */
            authorId: number;
            /** @description Liste des tags associés */
            tags?: components["schemas"]["BlogTagDto"][];
        };
        PostListResponseDto: {
            /** @description Liste des posts pour la page courante */
            posts: components["schemas"]["PostListItemDto"][];
            /**
             * @description Nombre total de posts publiés
             * @example 42
             */
            total: number;
            /**
             * @description Numéro de la page courante
             * @example 1
             */
            page: number;
            /**
             * @description Nombre de posts par page
             * @example 10
             */
            limit: number;
        };
        CommentResponseDto: {
            /**
             * @description Identifiant unique du commentaire
             * @example 1
             */
            id: number;
            /**
             * @description Contenu du commentaire
             * @example Great article!
             */
            content: string;
            /**
             * Format: date-time
             * @description Date de publication
             * @example 2024-01-01T00:00:00.000Z
             */
            publishedAt: string;
            /**
             * @description Identifiant du post associé
             * @example 1
             */
            postId: number;
            /**
             * @description Identifiant de l'auteur
             * @example 2
             */
            authorId: number;
        };
        PostDetailResponseDto: {
            /**
             * @description Identifiant unique du post
             * @example 1
             */
            id: number;
            /**
             * @description Titre du post
             * @example My Blog Post
             */
            title: string;
            /**
             * @description Slug URL-friendly du post
             * @example my-blog-post
             */
            slug: string;
            /**
             * @description Résumé du post
             * @example A brief summary
             */
            summary: string;
            /**
             * @description Contenu complet du post
             * @example Full content here...
             */
            content: string;
            /**
             * Format: date-time
             * @description Date de publication
             * @example 2024-01-01T00:00:00.000Z
             */
            publishedAt: string;
            /**
             * @description Identifiant de l'auteur
             * @example 1
             */
            authorId: number;
            /** @description Liste des tags associés */
            tags?: components["schemas"]["BlogTagDto"][];
            /** @description Commentaires associés au post */
            comments: components["schemas"]["CommentResponseDto"][];
        };
        CreateCommentDto: {
            /**
             * @description Contenu du commentaire (minimum 5 caractères, sans caractère "@")
             * @example Great article, very informative!
             */
            content: string;
            /**
             * @description Date de publication du commentaire (ISO 8601). Défaut : maintenant.
             * @example 2024-01-01T00:00:00.000Z
             */
            publishedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    SecurityController_getLoginForm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Données du formulaire de connexion */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginFormResponseDto"];
                };
            };
        };
    };
    SecurityController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Token JWT retourné */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenDto"];
                };
            };
            /** @description Identifiants invalides */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SecurityController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session terminée avec succès */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponseDto"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminBlogController_indexAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste des posts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponseDto"][];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Accès refusé (rôle insuffisant) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminBlogController_newForm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Formulaire vide */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePostDto"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminBlogController_newAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePostDto"];
            };
        };
        responses: {
            /** @description Post créé avec succès */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponseDto"];
                };
            };
            /** @description Données invalides (titre vide, contenu trop court…) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminBlogController_showAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du post */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Détails du post */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponseDto"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Post non trouvé */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminBlogController_editForm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du post */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Données du post pour édition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponseDto"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Post non trouvé */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminBlogController_editAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du post */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePostDto"];
            };
        };
        responses: {
            /** @description Post mis à jour */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponseDto"];
                };
            };
            /** @description Données invalides */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Post non trouvé */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminBlogController_deleteAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du post */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeletePostDto"];
            };
        };
        responses: {
            /** @description Post supprimé avec succès */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponseDto"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token CSRF invalide ou absent */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Post non trouvé */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BlogController_indexAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste paginée des articles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostListResponseDto"];
                };
            };
        };
    };
    BlogController_rssAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flux RSS valide (application/rss+xml) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    BlogController_pageAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numéro de page (entier ≥ 1) */
                page: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste paginée des articles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostListResponseDto"];
                };
            };
            /** @description Paramètre de page invalide (non numérique) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Page introuvable (au-delà des pages disponibles) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BlogController_postShowAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug URL-friendly de l'article */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Détail de l'article avec ses commentaires */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostDetailResponseDto"];
                };
            };
            /** @description Article introuvable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BlogController_commentNewAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug de l'article à commenter */
                postSlug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentDto"];
            };
        };
        responses: {
            /** @description Commentaire créé avec succès */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponseDto"];
                };
            };
            /** @description Contenu invalide (vide, trop court ou contient "@") */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Article introuvable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * Format: date-time
                         * @example 2024-01-15T12:00:00.000Z
                         */
                        timestamp?: string;
                    };
                };
            };
        };
    };
    SecurityController_getLoginForm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Données du formulaire de connexion */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginFormResponseDto"];
                };
            };
        };
    };
    SecurityController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Token JWT retourné */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenDto"];
                };
            };
            /** @description Identifiants invalides */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SecurityController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session terminée avec succès */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponseDto"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminBlogController_indexAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste des posts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponseDto"][];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Accès refusé (rôle insuffisant) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminBlogController_newForm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Formulaire vide */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePostDto"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminBlogController_newAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePostDto"];
            };
        };
        responses: {
            /** @description Post créé avec succès */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponseDto"];
                };
            };
            /** @description Données invalides (titre vide, contenu trop court…) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminBlogController_showAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du post */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Détails du post */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponseDto"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Post non trouvé */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminBlogController_editForm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du post */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Données du post pour édition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponseDto"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Post non trouvé */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminBlogController_editAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du post */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePostDto"];
            };
        };
        responses: {
            /** @description Post mis à jour */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponseDto"];
                };
            };
            /** @description Données invalides */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Post non trouvé */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminBlogController_deleteAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du post */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeletePostDto"];
            };
        };
        responses: {
            /** @description Post supprimé avec succès */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponseDto"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token CSRF invalide ou absent */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Post non trouvé */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BlogController_indexAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste paginée des articles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostListResponseDto"];
                };
            };
        };
    };
    BlogController_rssAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flux RSS valide (application/rss+xml) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    BlogController_pageAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numéro de page (entier ≥ 1) */
                page: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste paginée des articles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostListResponseDto"];
                };
            };
            /** @description Paramètre de page invalide (non numérique) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Page introuvable (au-delà des pages disponibles) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BlogController_postShowAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug URL-friendly de l'article */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Détail de l'article avec ses commentaires */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostDetailResponseDto"];
                };
            };
            /** @description Article introuvable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BlogController_commentNewAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug de l'article à commenter */
                postSlug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentDto"];
            };
        };
        responses: {
            /** @description Commentaire créé avec succès */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponseDto"];
                };
            };
            /** @description Contenu invalide (vide, trop court ou contient "@") */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Article introuvable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * Format: date-time
                         * @example 2024-01-15T12:00:00.000Z
                         */
                        timestamp?: string;
                    };
                };
            };
        };
    };
}
