// Auto-generated by src/scaffold/journey-playwright-generator.ts (in code-continuum).
// Do not edit manually — re-generated on every run of the e2e-journey phase.

export interface JourneyCredential {
  email: string
  password: string
  username?: string
  roles?: string[]
  label?: string
}

export const credentials: JourneyCredential[] = []
